config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :users
 resources :techwords, only: [:index, :show]
  
  get 'home/index'
root 'home#index'

namespace :admins do
	resources :techwords
	resources :categories
	resources :articles do
		resources :article_notes
 	end
end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/techword.rb
class Techword < ApplicationRecord
end

app/controllers/admins/techwords_controller.rb
class Admins::TechwordsController < ApplicationController
  before_action :set_techword, only: [:show, :edit, :update, :destroy]

  # GET /techwords
  # GET /techwords.json
  def index
    # @techwords = Techword.all
    @q = Techword.ransack(params[:q])
    @techwords = @q.result(distinct: true)  
  end

  # GET /techwords/1
  # GET /techwords/1.json
  def show
  end

  # GET /techwords/new
  def new
    @techword = Techword.new
  end

  # GET /techwords/1/edit
  def edit
  end

  # POST /techwords
  # POST /techwords.json
  def create
    @techword = Techword.new(techword_params)

    respond_to do |format|
      if @techword.save
        format.html { redirect_to admins_techword_path(@techword), notice: 'Techword was successfully created.' }
        format.json { render :show, status: :created, location: @techword }
      else
        format.html { render :new }
        format.json { render json: @techword.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /techwords/1
  # PATCH/PUT /techwords/1.json
  def update
    respond_to do |format|
      if @techword.update(techword_params)
        format.html { redirect_to admins_techword_path(@techword), notice: 'Techword was successfully updated.' }
        format.json { render :show, status: :ok, location: @techword }
      else
        format.html { render :edit }
        format.json { render json: @techword.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /techwords/1
  # DELETE /techwords/1.json
  def destroy
    @techword.destroy
    respond_to do |format|
      format.html { redirect_to admins_techwords_url, notice: 'Techword was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_techword
      @techword = Techword.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def techword_params
      params.require(:techword).permit(:name, :description)
    end
end

app/controllers/techwords_controller.rb
class TechwordsController < ApplicationController
  before_action :set_techword, only: [:show, :edit, :update, :destroy]

  def index
     @q = Techword.ransack(params[:q])
    @techwords = @q.result(distinct: true)  
  end

  def show
  end

 
  private
    def set_techword
      @techword = Techword.find(params[:id])
    end

 end

app/helpers/techwords_helper.rb
module TechwordsHelper
end

app/views/techwords/_form.html.erb
<%= form_for @techword, :html => { :class => "form-horizontal techword" } do |f| %>

  <% if @techword.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@techword.errors.count, "error") %> prohibited this techword from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @techword.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :description, :class => 'form-control ckeditor' %>
    </div>
    <%=f.error_span(:description) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                techwords_path, :class => 'btn btn-default' %>
    </div>
  </div>

  <script >
  $(document).ready(function(){
    $('.ckeditor').ckeditor({});
  });
</script>

<% end %>

app/views/techwords/edit.html.erb
<%- model_class = Techword -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/techwords/index.html.erb
<div class="table-responsive">
<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>description</th>
    </tr>
  </thead>
  <tbody>
    <% @techwords.each do |techword| %>
      <tr>
        <td><%= link_to techword.name, techword_path(techword) %></td>
        <td><%= techword.definition.html.safe %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/techwords/new.html.erb
<%- model_class = Techword -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/techwords/show.html.erb
<div class="page-header">
  <h1 class="text-center"><%= @techword.name  %></h1>
</div>

<%= @techword.description.html_safe %>

<%= link_to t('.back', :default => t("helpers.links.back")),
              root_path, :class => 'btn btn-default'  %>